Reverted back to libgoffixe-0-dev and skip patch 03_goffice_0-7-5_support for now (doesn't build) (re-opens #498775)
... partly reverted commit 1f316202c4744ae8a9cfbf7ce2bcb26742cc570c:
Apparently Gnucash 2.2.9 doesn't build with libgoffice-0-8-dev (0.7.15-1), and/or the patch 03_goffice_0-7-5_support is not complete:

/bin/sh ../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../.. -DG_LOG_DOMAIN=\"gnc.gui\"   -I../../src/core-utils -I../../src/gnc-module -I../../src/engine -I../../src/backend/file -I../../src/app-utils -I../../src -I../../src -I../../lib/libc -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -D_REENTRANT -I/usr/include/libglade-2.0 -I/usr/include/gtk-2.0 -I/usr/include/libxml2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_REENTRANT -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DORBIT2=1 -pthread -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/include/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/gnome-vfs-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/gtk-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/directfb -I/usr/include/libpng12 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgtkhtml-3.14 -I/usr/include/gtk-2.0 -I/usr/include/enchant -I/usr/include/gconf/2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include  -I../../lib/libqof/qof -I../../lib/libqof/qof -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgoffice-0.8 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/gtk-2.0 -I/usr/include/libglade-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gconf/2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include  -Wdeclaration-after-statement -Wno-pointer-sign -D_FORTIFY_SOURCE=2 -g -O2 -Wall -Wunused -Wmissing-prototypes -Wmissing-declarations  -Wno-unused -MT gnc-html-graph-gog.lo -MD -MP -MF .deps/gnc-html-graph-gog.Tpo -c -o gnc-html-graph-gog.lo gnc-html-graph-gog.c
rm: invalid argument: `'
 gcc -DHAVE_CONFIG_H -I. -I../.. -DG_LOG_DOMAIN=\"gnc.gui\" -I../../src/core-utils -I../../src/gnc-module -I../../src/engine -I../../src/backend/file -I../../src/app-utils -I../../src -I../../src -I../../lib/libc -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_REENTRANT -I/usr/include/libglade-2.0 -I/usr/include/gtk-2.0 -I/usr/include/libxml2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_REENTRANT -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DORBIT2=1 -pthread -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/include/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/gnome-vfs-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/gtk-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/directfb -I/usr/include/libpng12 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgtkhtml-3.14 -I/usr/include/gtk-2.0 -I/usr/include/enchant -I/usr/include/gconf/2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I../../lib/libqof/qof -I../../lib/libqof/qof -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgoffice-0.8 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/gtk-2.0 -I/usr/include/libglade-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gconf/2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -Wdeclaration-after-statement -Wno-pointer-sign -D_FORTIFY_SOURCE=2 -g -O2 -Wall -Wunused -Wmissing-prototypes -Wmissing-declarations -Wno-unused -MT gnc-html-graph-gog.lo -MD -MP -MF .deps/gnc-html-graph-gog.Tpo -c gnc-html-graph-gog.c  -fPIC -DPIC -o .libs/gnc-html-graph-gog.o
gnc-html-graph-gog.c: In function 'handle_piechart':
gnc-html-graph-gog.c:381: error: 'GOStyle' has no member named 'outline'
gnc-html-graph-gog.c:382: error: 'GOStyle' has no member named 'outline'
gnc-html-graph-gog.c:382: error: 'RGBA_BLACK' undeclared (first use in this function)
gnc-html-graph-gog.c:382: error: (Each undeclared identifier is reported only once
gnc-html-graph-gog.c:382: error: for each function it appears in.)
gnc-html-graph-gog.c: In function 'handle_barchart':
gnc-html-graph-gog.c:511: warning: implicit declaration of function 'GDK_TO_UINT'
make[6]: *** [gnc-html-graph-gog.lo] Error 1
make[6]: Leaving directory `/tmp/buildd/gnucash-2.2.9/src/gnome-utils'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/tmp/buildd/gnucash-2.2.9/src/gnome-utils'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/tmp/buildd/gnucash-2.2.9/src/gnome-utils'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/buildd/gnucash-2.2.9/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/buildd/gnucash-2.2.9'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/buildd/gnucash-2.2.9'
make: *** [build-stamp] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
pbuilder: Failed autobuilding of package
 -> Aborting with an error
 -> unmounting proc filesystem
 -> cleaning the build env
    -> removing directory /home/pbuilder/build//11854 and its subdirectories